name: Build and Test

on: 
  workflow_call:
    inputs: # https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
      dotnet-version:
        description: dotnet version
        type: string
        default: '6'
      filtered-test-category:
        description: Test category to filter out during testing
        type: string
        default: E2E

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    permissions:
      checks: write
      id-token: write
      contents: write
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
          dotnet-quality: ga
      - name: Cache nuget packages  # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: Test
        run: dotnet test --logger trx --results-directory "output/test" --filter Category!=${{ inputs.filtered-test-category }}
      - name: Test Report
        uses: dorny/test-reporter@v1.6.0
        if: always()
        with:
          name: test-report
          path: output/test/*.trx
          reporter: dotnet-trx